#!/usr/bin/env python3
"""Migrate archived bout chunks to the JAH-OLY-RECORD/2.0 envelope.

Adds (without touching battle semantics): engine_version, battle_version,
status, execution_mode, simulation_status, winner_status (+tiebreak on the 4
exact ties), stage_id/criteria_id/mission_id + versions, contender version +
source, structured findings with classes, invention status fields, and a
SHA-256 content_hash over the canonical record.

Copy-then-verify: every chunk is rewritten to tmp, verified field-by-field
against the original (ids, seeds, winners, margins, rounds, totals, narrative
must be byte-identical in value), then moved into place. The pre-migration
chunks remain in git history.
"""
import gzip, json, glob, hashlib, os, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, 'data')
CHUNKS = os.path.join(DATA, 'chunks')

def canon(obj):
    return json.dumps(obj, sort_keys=True, separators=(',', ':'),
                      ensure_ascii=False).encode('utf-8')

def content_hash(rec):
    r = {k: v for k, v in rec.items() if k != 'content_hash'}
    return 'sha256:' + hashlib.sha256(canon(r)).hexdigest()

# --- registries (frozen order, mirrors code/engine.js) ---
STAGE_KEYS = ['thunderdome', 'labyrinth', 'foundry', 'colosseum', 'abyss',
              'summit', 'bazaar', 'observatory', 'dojo', 'reef', 'citadel', 'pit']
CRIT_KEYS = ['scholar', 'sprinter', 'bard', 'engineer', 'sage', 'gladiator']
STAGE_IDS = {k: 'JAH-OLY-STAGE-%02d' % (i + 1) for i, k in enumerate(STAGE_KEYS)}
CRIT_IDS = {k: 'JAH-OLY-CRIT-%02d' % (i + 1) for i, k in enumerate(CRIT_KEYS)}

def get_missions():
    js = ("const E=require(%s);process.stdout.write(JSON.stringify(E.MISSIONS));"
          % json.dumps(os.path.join(HERE, 'engine.js')))
    p = subprocess.run(['node', '-e', js], capture_output=True, text=True)
    assert p.returncode == 0, p.stderr[:500]
    return json.loads(p.stdout)

MISSIONS = get_missions()
MIS_IDS = {m: 'JAH-OLY-MIS-%02d' % (i + 1) for i, m in enumerate(MISSIONS)}

roster = json.load(open(os.path.join(DATA, 'contenders.json')))
ROSTER_SRC = {c['id']: c.get('source', 'unknown') for c in roster}

def classify_finding(text, idx):
    t = text
    if 'Rematch recommendation' in t:
        return 'derived'
    if 'Hybrid vigor' in t:
        return 'speculative'
    if 'fought product-smooth' in t:
        return 'observed'
    if idx == 0:
        return 'calculated'
    if idx == 1:
        return 'observed'
    return 'calculated'

def envelop_contender(c):
    return {
        'id': c['id'], 'name': c['name'], 'type': c['type'],
        'blurb': c['blurb'], 'stats': c['stats'],
        'version': '1', 'source': ROSTER_SRC.get(c['id'], 'unknown'),
    }

def envelop(b):
    vals = list(b['totals'].values())
    tie = len(vals) == 2 and vals[0] == vals[1]
    nb = {
        'id': b['id'], 'n': b['n'], 'seed': b['seed'],
        'engine_version': '1',   # archived bouts were generated by engine v1
        'battle_version': 1,
        'status': 'ARCHIVED',
        'execution_mode': 'SIMULATED',
        'simulation_status': 'SIMULATED',
        'winner_status': 'WINNER',
    }
    if tie:
        nb['tiebreak'] = 'TIE_RULE_FIRST_LISTED'
    nb['contenders'] = [envelop_contender(c) for c in b['contenders']]
    stage = dict(b['stage'])
    stage['id'] = STAGE_IDS[stage['key']]
    stage['version'] = '1'
    nb['stage'] = stage
    crit = dict(b['criteria'])
    crit['id'] = CRIT_IDS[crit['key']]
    crit['version'] = '1'
    nb['criteria'] = crit
    nb['mission'] = b['mission']
    nb['mission_id'] = MIS_IDS[b['mission']]
    nb['mission_version'] = '1'
    nb['rounds'] = b['rounds']
    nb['totals'] = b['totals']
    nb['winner'] = envelop_contender(b['winner'])
    nb['loser'] = envelop_contender(b['loser'])
    nb['margin'] = b['margin']
    nb['narrative'] = b['narrative']
    nb['findings'] = [{'t': t, 'c': classify_finding(t, i)}
                      for i, t in enumerate(b['findings'])]
    invs = []
    for iv in b['inventions']:
        niv = dict(iv)
        niv['version'] = 1
        niv['record_type'] = 'DERIVED_INVENTION'
        niv['status'] = 'CONCEPT'
        invs.append(niv)
    nb['inventions'] = invs
    nb['content_hash'] = content_hash(nb)
    return nb

def verify(orig, new):
    for k in ('id', 'n', 'seed', 'margin', 'narrative', 'mission'):
        assert new[k] == orig[k], (orig['id'], k)
    assert new['winner']['id'] == orig['winner']['id']
    assert new['loser']['id'] == orig['loser']['id']
    assert new['totals'] == orig['totals']
    assert new['rounds'] == orig['rounds']
    assert new['stage']['key'] == orig['stage']['key']
    assert new['criteria']['key'] == orig['criteria']['key']
    assert [c['id'] for c in new['contenders']] == [c['id'] for c in orig['contenders']]
    assert [f['t'] for f in new['findings']] == orig['findings']
    assert [iv['id'] for iv in new['inventions']] == [iv['id'] for iv in orig['inventions']]
    # hash self-consistency
    assert new['content_hash'] == content_hash(new), orig['id']

def main():
    paths = sorted(glob.glob(os.path.join(CHUNKS, 'bouts-c*.jsonl.gz')))
    total, ties = 0, 0
    for p in paths:
        with gzip.open(p, 'rt', encoding='utf-8') as f:
            orig_lines = [l for l in f if l.strip()]
        orig_recs = [json.loads(l) for l in orig_lines]
        new_recs = [envelop(b) for b in orig_recs]
        for o, n in zip(orig_recs, new_recs):
            verify(o, n)
            total += 1
            if 'tiebreak' in n:
                ties += 1
        fd, tmp = tempfile.mkstemp(dir=CHUNKS, suffix='.tmp')
        os.close(fd)
        with gzip.open(tmp, 'wt', encoding='utf-8') as f:
            for n in new_recs:
                f.write(json.dumps(n, ensure_ascii=False) + '\n')
        # read back and re-verify from disk
        with gzip.open(tmp, 'rt', encoding='utf-8') as f:
            back = [json.loads(l) for l in f if l.strip()]
        assert len(back) == len(orig_recs), p
        for o, n in zip(orig_recs, back):
            verify(o, n)
        os.replace(tmp, p)
        print('migrated %s (%d bouts)' % (os.path.basename(p), len(new_recs)))
    print('MIGRATION OK: %d bouts across %d chunks; %d exact ties flagged'
          % (total, len(paths), ties))

if __name__ == '__main__':
    main()
